/********************************************
 * DO NOT EDIT THIS FILE
 * the verification process may break
 *******************************************/

require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

app.use(bodyParser.urlencoded({ extended: false })); // FCC boilerplate ใช้แค่ urlencoded
// app.use(bodyParser.json()); // ไม่จำเป็นสำหรับ FCC test แต่ถ้าอยากใช้ก็ได้

app.get("/", (req, res) => {
  res.send("FreeCodeCamp MongoDB Mongoose Project");
});

const listener = app.listen(process.env.PORT || 5000, () => {
  console.log("Your app is listening on port " + listener.address().port);
});

/********************************************
 * DO NOT EDIT THIS FILE
 * the verification process may break
 *******************************************/
